### ISSUE TITLE
11_Regression.ipynb

### ISSUE THREAD

**Issue by 2thespace** [AleksDevEdu/ml_edu#12]
## При выполнении 11_Regression не проходится последний тест.

```
Arrays are not almost equal to 7 decimals
ACTUAL: 0.49536088734115263
DESIRED: 0.5008875868218917
```

Единственная "самописная" функция при этом это  preprocess_data_high_poly

```
def preprocess_data_high_poly(DataFrame = pd.DataFrame, poly_coef= int):
    string = "hours_poly_"
    x = DataFrame.iloc[:,0]
    for i in range(poly_coef):
        col_name = string + str(i)
        DataFrame[col_name] = x**i
    return DataFrame
```

При этом так же имеется расхождение полученных цифр и текста:

![R2](https://github.com/2thespace/global_image/blob/main/issue_images/my_issue%20(4).jpg?raw=true)
![MAE](https://github.com/2thespace/global_image/blob/main/issue_images/my_issue%20(6).jpg?raw=true)
![Ratio](https://github.com/2thespace/global_image/blob/main/issue_images/my_issue%20(6).jpg?raw=true)

Во- время консультации подозрения были на различие в архитектуре, поэтому на всякий случай прикладываю дополнительную информацию:

![CPU](https://github.com/2thespace/global_image/blob/main/issue_images/my_issue%20(3).jpg?raw=true)
![PyVersion](https://github.com/2thespace/global_image/blob/main/issue_images/my_issue%20(1).jpg?raw=true)
![PipList](https://github.com/2thespace/global_image/blob/main/issue_images/my_issue%20(2).jpg?raw=true)

## У коллеги по курсу так же возникла схожая проблема, поэтому что бы не дублировать  issue прикладываю ее данные:

Тест:

```
AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 0.5010779274066266
 DESIRED: 0.5008875868218917
```

Код функции: 

```
def preprocess_data_high_poly(dataFrame, degree):
    poly = PolynomialFeatures(degree)

    x_data = dataFrame['hours'].values
    x_matrix = x_data.reshape(-1, 1)
    x_poly = poly.fit_transform(x_matrix)
  
    for i in range(0,degree+1):
        if i!=1:
            dataFrame["hours_poly_"+str(i)] = x_poly[:, i]

    return dataFrame

```

Результат:

![R2](https://github.com/2thespace/global_image/blob/main/issue_images/as_im5.jpg?raw=true)
![MAE](https://github.com/2thespace/global_image/blob/main/issue_images/as_im6.jpg?raw=true)
![Ratio](https://github.com/2thespace/global_image/blob/main/issue_images/as_im7.jpg?raw=true)

При этом еще в одном моменте произошло расхождение:

```
# TODO - реализуйте код расчета показателя и сравните с функцией r2_score
from sklearn.metrics import r2_score

def r2_score_manual(y_true, y_pred):
    n = len(y_true)
    mean_y = sum(y_true) / n
    SS_tot = sum((y_true - mean_y)**2)
    SS_res = sum((y_true - y_pred)**2)
    r2_value = 1 - SS_res/SS_tot
    return r2_value

my_r2 = r2_score_manual(y_true, y_pred)
print("my_r2 = ", my_r2)

lib_r2 = r2_score(y_true, y_pred)
print("lib_r2  = ", lib_r2)

my_r2 =  0.5587425113942917
lib_r2  =  0.5587425113942918
```

Различные данные:

![CPU](https://github.com/2thespace/global_image/blob/main/issue_images/as_im3.png?raw=true)
![PyVersion](https://github.com/2thespace/global_image/blob/main/issue_images/as_im1.png?raw=true)
![PipList](https://github.com/2thespace/global_image/blob/main/issue_images/my_issue%20(2).jpg?raw=true)

**Comment by KaiL4eK** [comment]
Ошибки в решениях не нашли, расширили проверку, если есть возможность поверить теперь - было бы отлично.

**Comment by 2thespace** [comment]
Теперь все норм. Тест проходится!
