### ISSUE TITLE
24_HW_Classification

### ISSUE THREAD

**Issue by MentimirIsakaev** [AleksDevEdu/ml_edu#13]
При переходе по ссылке:
![image](https://user-images.githubusercontent.com/112799917/197612156-8759e68b-ff0b-48c7-a73b-7ebd6a616e87.png)

Такой датасет отсутствует на Kaggle
![image](https://user-images.githubusercontent.com/112799917/197612442-34b49855-2c95-4f08-9c1d-a8cb73557a91.png)

**Comment by serykhelena** [comment]
https://www.kaggle.com/datasets/redwankarimsony/heart-disease-data

**Comment by KaiL4eK** [comment]
https://www.kaggle.com/datasets/cherngs/heart-disease-cleveland-uci
Последний актуальный
